// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewProjectTest.Data;

namespace NewProjectTest.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20220510200349_addItemsToDatabase")]
    partial class addItemsToDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("NewProjectTest.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Office")
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("CutDate")
                        .HasColumnType("date");
                    b.Property<string>("Switch1")
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("Switch2")
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("Host Clli")
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("Old Clli")
                       .HasColumnType("nvarchar(max)");
                    b.Property<string>("New Clli")
                       .HasColumnType("nvarchar(max)");
                    b.Property<string>("Project Manager")
                       .HasColumnType("nvarchar(max)");
                    b.Property<string>("LCS Manager")
                       .HasColumnType("nvarchar(max)");
                    b.Property<string>("DTR Manager")
                       .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CoConversion");
                });
#pragma warning restore 612, 618
        }
    }
}
